os:
  - linux
  - osx
# TODO: Uncomment when tests running on Windows.
#  - windows

addons:
  apt:
    packages:
    - tree
  homebrew:
    packages:
    - tree
    update: true

# Only clone the most recent commit.
git:
  depth: 1

language: go

go:
  - "1.12"

go_import_path: sigs.k8s.io/kustomize

before_install:
  - source ./travis/consider-early-travis-exit.sh
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.17.1
  - go get -u github.com/monopole/mdrip
  # The following would install Helm if needed for some reason.
  # - wget https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz
  # - tar -xvzf helm-v2.13.1-linux-amd64.tar.gz
  # - sudo mv linux-amd64/helm /usr/local/bin/helm

# Skip the install process; let pre-commit.sh do it.
install: true

script:
  - ./travis/pre-commit.sh

# TBD. Suppressing for now.
notifications:
  email: false
