apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-search-ui
spec:
  selector:
    matchLabels:
      app: kustomize-search
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: kustomize-search
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/kustomize-search/frontend:latest
        imagePullPolicy: Always
        ports:
        - name: frontend-port
          containerPort: 80
