apiVersion: v1beta1
kind: Kustomization
bases:
- ../../base
namePrefix: staging-
configMapGenerator:
- name: demo-configmap
  behavior: merge
  files:
    - application.properties
  literals:
    - foo=bar
  env: staging.env
