name: release-kyaml

on: 
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: release type (major, minor, or patch).
        options:
          - major
          - minor
          - patch
        required: true
      release_branch:
        type: string
        description: release branch name "release-kyaml-v*"
        required: true

jobs:
  pre-build: 
    name: Pre-build
    runs-on: ubuntu-latest
    outputs:
        unit_test_result: ${{ steps.unit_test.outputs }}
    steps:
      - name: Fetch changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release_branch }}
      - name: Unit test
        id: unit_test
        run: |
          echo "Executing unit test"
          make test-unit-all >> "${GITHUB_OUTPUT}"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build test
        run: |
          make install-local-tools
          make build-kustomize-api
  e2e-test:
    name: End-to-end Testing
    runs-on: ubuntu-latest
    steps:
      - name: End-to-end testing   
        run: make verify-kustomize-e2e
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release kyaml
        run: |
          make install-local-tools
          gorepomod release kyaml ${{ inputs.release_type }}
